// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using myIoTGrid.Hub.Infrastructure.Data;

#nullable disable

namespace myIoTGrid.Hub.Infrastructure.Migrations
{
    [DbContext(typeof(HubDbContext))]
    partial class HubDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("AcknowledgedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AlertTypeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("HubId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendation")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<int>("Source")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AlertTypeId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("HubId");

                    b.HasIndex("IsActive");

                    b.HasIndex("Level");

                    b.HasIndex("NodeId");

                    b.HasIndex("Source");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "IsActive");

                    b.HasIndex("TenantId", "Level", "IsActive");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.AlertType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DefaultLevel")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsGlobal");

                    b.ToTable("AlertTypes", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Hub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HubId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("IsOnline");

                    b.HasIndex("LastSeen");

                    b.HasIndex("TenantId");

                    b.HasIndex("TenantId", "HubId")
                        .IsUnique();

                    b.ToTable("Hubs", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Node", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("BatteryLevel")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FirmwareVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("HubId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Protocol")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HubId");

                    b.HasIndex("IsOnline");

                    b.HasIndex("LastSeen");

                    b.HasIndex("NodeId");

                    b.HasIndex("HubId", "NodeId")
                        .IsUnique();

                    b.ToTable("Nodes", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Reading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSyncedToCloud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("IsSyncedToCloud");

                    b.HasIndex("NodeId");

                    b.HasIndex("SensorTypeId");

                    b.HasIndex("TenantId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("NodeId", "Timestamp");

                    b.HasIndex("TenantId", "Timestamp");

                    b.HasIndex("NodeId", "SensorTypeId", "Timestamp");

                    b.ToTable("Readings", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Sensor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("EndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SensorTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("NodeId");

                    b.HasIndex("SensorTypeId");

                    b.HasIndex("NodeId", "EndpointId")
                        .IsUnique();

                    b.ToTable("Sensors", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SensorType", b =>
                {
                    b.Property<string>("TypeId")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("other");

                    b.Property<uint>("ClusterId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCustom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsGlobal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<string>("MatterClusterName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("MaxValue")
                        .HasColumnType("REAL");

                    b.Property<double?>("MinValue")
                        .HasColumnType("REAL");

                    b.Property<double>("Resolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("REAL")
                        .HasDefaultValue(0.10000000000000001);

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("TypeId");

                    b.HasIndex("Category");

                    b.HasIndex("ClusterId");

                    b.HasIndex("IsCustom");

                    b.HasIndex("IsGlobal");

                    b.ToTable("SensorTypes", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SyncedNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CloudNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOnline")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceDetails")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CloudNodeId")
                        .IsUnique();

                    b.HasIndex("IsOnline");

                    b.HasIndex("LastSyncAt");

                    b.HasIndex("NodeId");

                    b.HasIndex("Source");

                    b.ToTable("SyncedNodes", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SyncedReading", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SensorTypeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SyncedNodeId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("SensorTypeId");

                    b.HasIndex("SyncedAt");

                    b.HasIndex("SyncedNodeId");

                    b.HasIndex("Timestamp");

                    b.HasIndex("SyncedNodeId", "Timestamp");

                    b.HasIndex("SyncedNodeId", "SensorTypeId", "Timestamp");

                    b.ToTable("SyncedReadings", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CloudApiKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSyncAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tenants", (string)null);
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Alert", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.AlertType", "AlertType")
                        .WithMany("Alerts")
                        .HasForeignKey("AlertTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Hub", "Hub")
                        .WithMany("Alerts")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Node", "Node")
                        .WithMany("Alerts")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Alerts")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AlertType");

                    b.Navigation("Hub");

                    b.Navigation("Node");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Hub", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Hubs")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Node", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Hub", "Hub")
                        .WithMany("Nodes")
                        .HasForeignKey("HubId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("myIoTGrid.Hub.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("NodeId")
                                .HasColumnType("TEXT");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Longitude");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Name");

                            b1.HasKey("NodeId");

                            b1.ToTable("Nodes");

                            b1.WithOwner()
                                .HasForeignKey("NodeId");
                        });

                    b.Navigation("Hub");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Reading", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Node", "Node")
                        .WithMany("Readings")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Readings")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Sensor", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.Node", "Node")
                        .WithMany("Sensors")
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.SensorType", "SensorType")
                        .WithMany("Sensors")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Node");

                    b.Navigation("SensorType");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SyncedNode", b =>
                {
                    b.OwnsOne("myIoTGrid.Hub.Domain.ValueObjects.Location", "Location", b1 =>
                        {
                            b1.Property<Guid>("SyncedNodeId")
                                .HasColumnType("TEXT");

                            b1.Property<double?>("Latitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Latitude");

                            b1.Property<double?>("Longitude")
                                .HasColumnType("REAL")
                                .HasColumnName("Location_Longitude");

                            b1.Property<string>("Name")
                                .HasMaxLength(200)
                                .HasColumnType("TEXT")
                                .HasColumnName("Location_Name");

                            b1.HasKey("SyncedNodeId");

                            b1.ToTable("SyncedNodes");

                            b1.WithOwner()
                                .HasForeignKey("SyncedNodeId");
                        });

                    b.Navigation("Location");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SyncedReading", b =>
                {
                    b.HasOne("myIoTGrid.Hub.Domain.Entities.SensorType", "SensorType")
                        .WithMany("SyncedReadings")
                        .HasForeignKey("SensorTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("myIoTGrid.Hub.Domain.Entities.SyncedNode", "SyncedNode")
                        .WithMany("SyncedReadings")
                        .HasForeignKey("SyncedNodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SensorType");

                    b.Navigation("SyncedNode");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.AlertType", b =>
                {
                    b.Navigation("Alerts");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Hub", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Node", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");

                    b.Navigation("Sensors");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SensorType", b =>
                {
                    b.Navigation("Readings");

                    b.Navigation("Sensors");

                    b.Navigation("SyncedReadings");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.SyncedNode", b =>
                {
                    b.Navigation("SyncedReadings");
                });

            modelBuilder.Entity("myIoTGrid.Hub.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Hubs");
                });
#pragma warning restore 612, 618
        }
    }
}
